background: '#212121'
blue: '#00347d'
dark_background: '#000000'
dark_purple: '#5a0066'
foreground: '#e6e6e6'
gray: '#212121'
hover_default: '#2e2e2e'
light_gray: '#2e2e2e'
light_hover: '#d0ced9'
purple: '#870099'
red: '#7d0000'
royal_blue: '#0f68db'
standard_icon_size: 25px
style_color: '#212121'
